In [2]:
import pandas as pd
import numpy as np
import time

In [8]:
import os

print(os.path.exists(r"C:\Users\HYPE AMD\Downloads\Dataset nilai siswa.xlsx"))

True

In [10]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [11]:
import pandas as pd

df = pd.read_excel(
    r"C:\Users\HYPE AMD\Downloads\Dataset nilai siswa.xlsx"
)

df.head()

,Nama,Matematika,Fisika,Biologi,Kimia,Bahasa Inggris,Bahasa Indonesia,Sejarah,PKN,Ekonomi,Sosiologi
0,Aldo,80.0,78.0,85.0,82.0,76.0,88.0,79.0,90.0,81.0,82.0
1,Bella,90.0,92.0,89.0,91.0,87.0,93.0,88.0,95.0,90.0,91.0
2,Cahyo,70.0,75.0,72.0,68.0,74.0,80.0,73.0,78.0,71.0,72.0
3,Dina,85.0,88.0,84.0,86.0,82.0,90.0,84.0,91.0,87.0,86.0
4,Eko,76.0,74.0,78.0,72.0,75.0,77.0,74.0,79.0,76.0,75.0

In [12]:
print(df.columns)

Index(['Nama', 'Matematika', 'Fisika', 'Biologi', 'Kimia', 'Bahasa Inggris',
       'Bahasa Indonesia', 'Sejarah', 'PKN', 'Ekonomi', 'Sosiologi'],
      dtype='str')

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Nama              102 non-null    str
 1   Matematika        101 non-null    float64
 2   Fisika            101 non-null    float64
 3   Biologi           101 non-null    float64
 4   Kimia             101 non-null    float64
 5   Bahasa Inggris    101 non-null    float64
 6   Bahasa Indonesia  101 non-null    float64
 7   Sejarah           101 non-null    float64
 8   PKN               101 non-null    float64
 9   Ekonomi           101 non-null    float64
 10  Sosiologi         101 non-null    float64
dtypes: float64(10), str(1)
memory usage: 9.0 KB

In [14]:
import time

start_time = time.perf_counter()

In [15]:
sains = [
    "Matematika",
    "Fisika",
    "Biologi",
    "Kimia"
]

sosial = [
    "Sejarah",
    "PKN",
    "Ekonomi",
    "Sosiologi"
]

bahasa = [
    "Bahasa Inggris",
    "Bahasa Indonesia"
]

semua_mapel = sains + sosial + bahasa

In [16]:
df["Rata_Rata"] = df[semua_mapel].mean(axis=1)

df[
    ["Nama", "Rata_Rata"]
].head()

    Nama  Rata_Rata
0   Aldo       82.1
1  Bella       90.6
2  Cahyo       73.3
3   Dina       86.3
4    Eko       75.6

In [17]:
df["Rata_Sains"] = df[sains].mean(axis=1)

df["Rata_Sosial"] = df[sosial].mean(axis=1)

df["Rata_Bahasa"] = df[bahasa].mean(axis=1)

df[
    [
        "Nama",
        "Rata_Sains",
        "Rata_Sosial",
        "Rata_Bahasa"
    ]
].head()

    Nama  Rata_Sains  Rata_Sosial  Rata_Bahasa
0   Aldo       81.25         83.0         82.0
1  Bella       90.50         91.0         90.0
2  Cahyo       71.25         73.5         77.0
3   Dina       85.75         87.0         86.0
4    Eko       75.00         76.0         76.0

In [18]:
def bidang_dominan(row):

    nilai = {
        "Sains": row["Rata_Sains"],
        "Sosial": row["Rata_Sosial"],
        "Bahasa": row["Rata_Bahasa"]
    }

    return max(nilai, key=nilai.get)

df["Bidang_Dominan"] = df.apply(
    bidang_dominan,
    axis=1
)

df[
    [
        "Nama",
        "Bidang_Dominan"
    ]
].head()

    Nama Bidang_Dominan
0   Aldo         Sosial
1  Bella         Sosial
2  Cahyo         Bahasa
3   Dina         Sosial
4    Eko         Sosial

In [19]:
def rekomendasi_jurusan(bidang):

    if bidang == "Sains":
        return "Teknik Informatika"

    elif bidang == "Sosial":
        return "Manajemen"

    else:
        return "Sastra Inggris"

df["Rekomendasi_Jurusan"] = (
    df["Bidang_Dominan"]
    .apply(rekomendasi_jurusan)
)

In [20]:
KKM = 75

df["Status"] = df["Rata_Rata"].apply(
    lambda x:
    "Lulus"
    if x >= KKM
    else "Tidak Lulus"
)

In [21]:
tertinggi = df.loc[
    df["Rata_Rata"].idxmax()
]

terendah = df.loc[
    df["Rata_Rata"].idxmin()
]

print("Siswa Terbaik")
print(
    tertinggi["Nama"],
    round(tertinggi["Rata_Rata"],2)
)

print()

print("Siswa Terendah")
print(
    terendah["Nama"],
    round(terendah["Rata_Rata"],2)
)

Siswa Terbaik
Zahra 95.1

Siswa Terendah
Wira 67.1

In [22]:
print(
    df["Bidang_Dominan"]
    .value_counts()
)

Bidang_Dominan
Sosial    58
Bahasa    43
Sains      2
Name: count, dtype: int64

In [23]:
end_time = time.perf_counter()

print(
    "Waktu Eksekusi:",
    end_time - start_time,
    "detik"
)

Waktu Eksekusi: 127.58858519996284 detik

In [24]:
hasil = df[
    [
        "Nama",
        "Rata_Rata",
        "Rata_Sains",
        "Rata_Sosial",
        "Rata_Bahasa",
        "Bidang_Dominan",
        "Rekomendasi_Jurusan",
        "Status"
    ]
]

hasil.head(20)

,Nama,Rata_Rata,Rata_Sains,Rata_Sosial,Rata_Bahasa,Bidang_Dominan,Rekomendasi_Jurusan,Status
0,Aldo,82.1,81.25,83.00,82.0,Sosial,Manajemen,Lulus
1,Bella,90.6,90.50,91.00,90.0,Sosial,Manajemen,Lulus
2,Cahyo,73.3,71.25,73.50,77.0,Bahasa,Sastra Inggris,Tidak Lulus
3,Dina,86.3,85.75,87.00,86.0,Sosial,Manajemen,Lulus
4,Eko,75.6,75.00,76.00,76.0,Sosial,Manajemen,Lulus
5,Fina,92.7,93.00,93.50,90.5,Sosial,Manajemen,Lulus
6,Gilang,68.9,65.75,69.75,73.5,Bahasa,Sastra Inggris,Tidak Lulus
7,Hani,80.3,78.50,81.25,82.0,Bahasa,Sastra Inggris,Lulus
8,Iqbal,87.6,87.50,87.75,87.5,Sosial,Manajemen,Lulus
9,Jihan,76.9,74.50,78.25,79.0,Bahasa,Sastra Inggris,Lulus
10,Kevin,81.7,80.50,83.25,81.0,Sosial,Manajemen,Lulus
11,Laras,91.5,90.50,92.75,91.0,Sosial,Manajemen,Lulus
12,Miko,70.9,69.75,71.25,72.5,Bahasa,Sastra Inggris,Tidak Lulus
13,Nina,85.3,84.50,86.25,85.0,Sosial,Manajemen,Lulus
14,Oki,76.2,75.50,77.25,75.5,Sosial,Manajemen,Lulus
15,Putri,93.3,92.50,94.50,92.5,Sosial,Manajemen,Lulus
16,Raka,69.4,67.25,70.00,72.5,Bahasa,Sastra Inggris,Tidak Lulus
17,Salsa,81.3,79.50,82.25,83.0,Bahasa,Sastra Inggris,Lulus
18,Teguh,88.1,87.50,89.00,87.5,Sosial,Manajemen,Lulus
19,Uli,74.5,72.50,75.25,77.0,Bahasa,Sastra Inggris,Tidak Lulus